import { 
  Home, Menu, X, Search, Settings, User, Bell, Mail,
  ChevronLeft, ArrowRight, Move, CornerDownLeft,
  Check, Plus, Edit, Trash, Copy, Share, Download,
  AlertCircle, CheckCircle, Info, HelpCircle,
  Facebook, Twitter, Instagram, Youtube, Linkedin, Github,
  ShoppingCart, CreditCard, TrendingUp, BarChart,
  Palette, Brush, Wand, Sparkles, Flame, Zap,
  Pizza, Coffee, Beer, Cake, IceCream, Cookie,
  Target, Crosshair, Shield, Swords, Trophy, Medal,
  Gamepad2, Monitor, Clock, Calendar, MapPin, Phone,
  Send, MessageSquare, Bot, Users, Star, Heart,
  Eye, Play, Pause, Volume2, VolumeX, Maximize,
  Filter, SortAsc, Grid, List, LayoutGrid,
  Skull, Bomb, Radio, Headphones, Mic, MicOff,
  Flag, Map, Navigation, Compass, Globe,
  ChevronDown, ChevronUp, ArrowUp, ArrowDown,
  RefreshCw, RotateCcw, Loader2, Activity,
  Lock, Unlock, Key, LogIn, LogOut,
  FileText, Image, Video, Music, File,
  Folder, Archive, Upload, Cloud, Database,
  Wifi, Bluetooth, Battery, BatteryCharging,
  Sun, Moon, MonitorPlay, Tv, Smartphone,
  Laptop, Mouse, Keyboard, Printer, Camera,
  ShoppingBag, Tag, Percent, Gift, Award,
  Briefcase, Building, Landmark, Wallet,
  Plane, Car, Bus, Train, Ship, Truck,
  HomeIcon, Building2, Store, Warehouse,
  TreePine, Flower2, Mountain, Waves, CloudSun,
  Thermometer, Droplets, Wind, CloudRain, Snowflake,
  AlertTriangle, AlertOctagon, ShieldAlert,
  HelpSquare, BookOpen, GraduationCap, Lightbulb,
  Puzzle, Blocks, Box, Package, Container,
  Scissors, PenTool, Type, AlignLeft, AlignCenter,
  Bold, Italic, Underline, Link, Paperclip,
  MoreHorizontal, MoreVertical, GripVertical,
  Minus, Divide, Equal, Percent as PercentIcon,
  Hash, At, DollarSign, Euro, PoundSterling,
  Bitcoin, Banknote, Coins, Receipt,
  QrCode, Barcode, Scan, ScanLine,
  Fingerprint, FaceId, ScanFace,
  Accessibility, Ear, EyeOff, Glasses,
  HeartPulse, ActivitySquare, Stethoscope,
  Pill, Syringe, ThermometerSnowflake,
  Dumbbell, Bike, Swim, Footprints,
  Tent, Campfire, Fish, Beef, Apple,
  Cherry, Grape, Citrus, Carrot,
  Utensils, ForkKnife, Soup, Salad,
  Sandwich, Hamburger, Hotdog, Fries,
  Popcorn, Donut, CupSoda, Wine,
  GlassWater, Milk, Egg, Croissant,
  Toast, Soup2, Drumstick, Bacon,
  Anchor, LifeBuoy, Flashlight, TentTree,
  Binoculars, Telescope, Microscope,
  FlaskConical, Atom, Dna, BrainCircuit,
  Cpu, HardDrive, Server, Router,
  Ethernet, Usb, Hdmi, BatteryMedium,
  Plug, ZapOff, Power, PowerOff,
  SunDim, Sunrise, Sunset, MoonStar,
  CloudFog, CloudLightning, Tornado,
  ThermometerSun, Snowman, FlameKindling,
  Droplet, Waves2, Tsunami, Flood,
  Earthquake, Volcano, Hurricane,
  Radiation, Biohazard, ShieldCheck,
  ShieldX, ShieldQuestion, LockKeyhole,
  UnlockKeyhole, KeyRound, KeySquare,
  Fingerprint2, ScanEye, ScanFace2,
  Glasses2, Sunglasses, Contact2,
  EarOff, HearingImpaired, Brain,
  HeartCrack, HeartHandshake, HeartMinus,
  HeartPlus, HeartOff, Activity2,
  Stethoscope2, Thermometer2, Pill2,
  Capsules, Tablets, Syringe2, Droplets2,
  Bandage, Bone, Wheelchair,
  Accessibility2, PersonStanding,
  Baby, User2, Users2, UserPlus,
  UserMinus, UserX, UserCheck,
  UserCog, UserRound, UsersRound,
  MessageCircle, MessagesSquare,
  MessageSquarePlus, MessageSquareMinus,
  MessageSquareX, MessageSquareDashed,
  MailPlus, MailMinus, MailX, MailCheck,
  MailQuestion, MailWarning, Inbox,
  Send2, SendHorizontal, Reply, ReplyAll,
  Forward, Trash2, ArchiveRestore,
  ArchiveX, Archive2, Inbox2,
  FolderOpen, FolderMinus, FolderPlus,
  FolderX, FolderCheck, FolderCog,
  FolderTree, FolderArchive, FolderGit,
  FolderGit2, FolderKanban, FolderClock,
  FilePlus, FileMinus, FileX, FileCheck,
  FileCog, FileType, FileJson, FileCode,
  FileText2, FileImage, FileVideo2,
  FileAudio2, FileArchive, FileUp,
  FileDown, FileClock, FileSearch,
  FileQuestion, FileWarning, FileX2,
  FileHeart, FileStack, FileSymlink,
  FileInput, FileOutput, FileKey,
  FileLock, FileCheck2, FilePlus2,
  FileMinus2, FileX3, FileCog2,
  FileType2, FileJson2, FileCode2,
  Clipboard, ClipboardCopy, ClipboardList,
  ClipboardCheck, ClipboardX, ClipboardType,
  ClipboardPaste, Copy2, CopyCheck,
  CopyPlus, CopyMinus, CopyX, Scissors2,
  AlignJustify, AlignRight, AlignLeft2,
  AlignCenter2, AlignStart, AlignEnd,
  AlignCenterVertical, AlignCenterHorizontal,
  Space, Indent, Outdent, WrapText,
  ListOrdered, List, ListChecks, ListX,
  ListPlus, ListMinus, ListStart,
  ListEnd, ListTree, ListVideo,
  ListMusic, ListCollapse, ListRestart,
  Pilcrow, Quote, Code, Code2, Terminal,
  TerminalSquare, Command, Keyboard2,
  MousePointer2, MousePointerClick,
  Pointer, Grab, Hand, HandMetal,
  RockingChair, Armchair, Bed, BedDouble,
  Bath, ShowerHead, Sink, Toilet,
  Lamp, LampCeiling, LampDesk, LampFloor,
  LampWallDown, LampWallUp, Lightbulb2,
  Flashlight2, Cctv, Camera2, CameraOff,
  Video2, VideoOff, ScreenShare, ScreenShareOff,
  Monitor2, MonitorOff, MonitorSmartphone,
  MonitorSpeaker, MonitorPlay2, MonitorPause,
  Tv2, TvOff, Smartphone2, SmartphoneOff,
  Tablet, Tablet2, Laptop2, LaptopOff,
  Mouse2, MouseOff, Keyboard3, KeyboardOff,
  Printer2, PrinterOff, Scanner, Shredder,
  Cast, CastOff, Airplay, Airplay2,
  Radiation2, Radio2, RadioReceiver,
  RadioTower, Antenna, Satellite,
  SatelliteDish, Radar, Waves3, Signal,
  SignalHigh, SignalMedium, SignalLow,
  SignalZero, Wifi2, WifiOff, WifiZero,
  Ethernet2, Router2, Server2, ServerOff,
  ServerCog, ServerCrash, HardDrive2,
  HardDriveDownload, HardDriveUpload,
  Database2, DatabaseBackup, DatabaseZap,
  Cloud2, CloudOff, CloudDownload,
  CloudUpload, CloudRain2, CloudSnow,
  CloudLightning2, CloudFog2, CloudSun2,
  CloudMoon, Cloudy, Sun2, Sunrise2,
  Sunset2, Moon2, MoonStar2, Star2,
  StarOff, Sparkles2, Zap2, ZapOff2,
  Battery2, BatteryFull, BatteryLow,
  BatteryWarning, BatteryCharging2,
  Plug2, PlugZap, Power2, PowerOff2,
  ToggleLeft, ToggleRight, Toggle2,
  Slider, SlidersHorizontal, SlidersVertical,
  Joystick, Gamepad, Gamepad2 as GamepadIcon,
  Dices, Dice1, Dice2, Dice3, Dice4,
  Dice5, Dice6, Diamond, Club, Spade,
  Heart2, Heart3, Heart4, Heart5,
  Crown, Trophy2, Medal2, Award2,
  Medal3, Medal4, Award3, Star3,
  ThumbsUp, ThumbsDown, Smile, Frown,
  Meh, Laugh, Annoyed, Angry,
  AlertCircle2, AlertTriangle2, Info2,
  HelpCircle2, XCircle, XOctagon,
  XSquare, CheckCircle2, CheckSquare,
  CheckSquare2, MinusCircle, MinusSquare,
  PlusCircle, PlusSquare, DivideCircle,
  DivideSquare, Equal2, NotEqual,
  GreaterThan, LessThan, Infinity,
  Pi, Sigma, Function, Calculator,
  Binary, Hexagon, Pentagon, Octagon,
  Square, Circle, Triangle, Diamond2,
  Trapezoid, Parallelogram, Ellipsis,
  Minus2, Plus2, Divide2, Percent2,
  Hash2, At2, Ampersand, Asterisk,
  Quote2, Apostrophe, Braces, Brackets,
  Parentheses, AngleBracket, CurlyBraces,
  Slash, Backslash, BarChart2, BarChart3,
  BarChart4, BarChartHorizontal,
  PieChart, LineChart, AreaChart,
  ScatterChart, RadarChart, HeatMap,
  GanttChart, Kanban, Workflow, GitBranch,
  GitCommit, GitMerge, GitPullRequest,
  GitCompare, GitFork, GitGraph,
  Github2, Gitlab, Bitbucket, Codepen,
  Codesandbox, Stackblitz, Vercel2,
  Netlify, Heroku, Aws, Azure,
  GoogleCloud, Firebase2, Supabase,
  MongoDb, Postgresql, Mysql, Redis,
  Docker, Kubernetes, Jenkins,
  GithubActions, GitlabCi, TravisCi,
  CircleCi, Code2 as CodeIcon,
  Terminal2, Shell, Powershell, Bash,
  Python, JavaScript2, TypeScript2,
  React2, Vue, Angular, Svelte,
  Nextjs, Nuxtjs, Gatsby, Remix,
  Tailwind2, Bootstrap, MaterialUi,
  ChakraUi, AntDesign, StyledComponents,
  Framer2, Threejs, D3, Chartjs,
  ECharts, Highcharts, ApexCharts,
  Recharts, Victory, Nivo,
  Mermaid, PlantUml, Drawio,
  Figma2, Sketch, AdobeXd,
  Photoshop, Illustrator, Premiere,
  AfterEffects, Lightroom, Indesign,
  Blender, Cinema4d, Maya, Sketchup,
  Autocad, Solidworks, Fusion360,
  Onshape, Tinkercad, Thingiverse,
  OctoPrint, Klipper, Marlin,
  RepRap, Prusa, BambuLab,
  Creality, Elegoo, Anycubic,
  Ultimaker, Makerbot, Formlabs,
  Laser, Cnc, 3dPrint, Robotics,
  Arduino, RaspberryPi, Esp32,
  Stm32, Avr, Pic, Arm, Riscv,
  Fpga, Asic, Pcb, Circuit,
  Oscilloscope, Multimeter, PowerSupply,
  Soldering, Welding, Machining,
  Carpentry, Masonry, Plumbing,
  Electrical, Hvac, Solar,
  WindTurbine, BatteryBank, Inverter,
  ChargeController, Generator,
  Transformer, Substation, Grid,
  Meter, Breaker, Fuse, Relay,
  Contactor, Switch, Outlet,
  Light, Fan, Pump, Motor,
  Compressor, Conveyor, Robot,
  CncMill, Lathe, Grinder, Saw,
  Drill, Router3, Planer, Sander,
  Welder, Plasma, Laser2, Waterjet,
  Press, Brake, Shear, Roll,
  Extruder, Injection, Blow,
  Thermoform, Rotational, Composite,
  CarbonFiber, Fiberglass, Kevlar,
  Aluminum, Steel, Titanium,
  Copper, Brass, Bronze, Zinc,
  Nickel, Chrome, Gold, Silver,
  Platinum, Palladium, Rhodium,
  Silicon, Germanium, Gallium,
  Arsenic, Selenium, Tellurium,
  Cadmium, Mercury, Lead, Tin,
  Antimony, Bismuth, Polonium,
  Astatine, Radon, Francium,
  Radium, Actinium, Thorium,
  Protactinium, Uranium, Neptunium,
  Plutonium, Americium, Curium,
  Berkelium, Californium, Einsteinium,
  Fermium, Mendelevium, Nobelium,
  Lawrencium, Rutherfordium, Dubnium,
  Seaborgium, Bohrium, Hassium,
  Meitnerium, Darmstadtium, Roentgenium,
  Copernicium, Nihonium, Flerovium,
  Moscovium, Livermorium, Tennessine,
  Oganesson, Hydrogen, Helium,
  Lithium, Beryllium, Boron, Carbon,
  Nitrogen, Oxygen, Fluorine, Neon,
  Sodium, Magnesium, Aluminum2, Silicon2,
  Phosphorus, Sulfur, Chlorine, Argon,
  Potassium, Calcium, Scandium, Titanium2,
  Vanadium, Chromium, Manganese, Iron,
  Cobalt, Nickel2, Copper2, Zinc2,
  Gallium2, Germanium2, Arsenic2,
  Selenium2, Bromine, Krypton, Rubidium,
  Strontium, Yttrium, Zirconium, Niobium,
  Molybdenum, Technetium, Ruthenium,
  Rhodium2, Palladium2, Silver2, Cadmium2,
  Indium, Tin2, Antimony2, Tellurium2,
  Iodine, Xenon, Cesium, Barium, Lanthanum,
  Cerium, Praseodymium, Neodymium,
  Promethium, Samarium, Europium,
  Gadolinium, Terbium, Dysprosium,
  Holmium, Erbium, Thulium, Ytterbium,
  Lutetium, Hafnium, Tantalum, Tungsten,
  Rhenium, Osmium, Iridium, Platinum2,
  Gold2, Mercury2, Thallium, Lead2,
  Bismuth2, Polonium2, Astatine2, Radon2,
  Francium2, Radium2, Actinium2, Thorium2,
  Protactinium2, Uranium2, Neptunium2,
  Plutonium2, Americium2, Curium2,
  Berkelium2, Californium2, Einsteinium2,
  Fermium2, Mendelevium2, Nobelium2,
  Lawrencium2, Rutherfordium2, Dubnium2,
  Seaborgium2, Bohrium2, Hassium2,
  Meitnerium2, Darmstadtium2, Roentgenium2,
  Copernicium2, Nihonium2, Flerovium2,
  Moscovium2, Livermorium2, Tennessine2,
  Oganesson2
} from 'lucide-react';

const iconMap = {
  Home, Menu, X, Search, Settings, User, Bell, Mail,
  'chevron-left': ChevronLeft, 'arrow-right': ArrowRight, Move, 'corner-down-left': CornerDownLeft,
  Check, Plus, Edit, Trash, Copy, Share, Download,
  'alert-circle': AlertCircle, 'check-circle': CheckCircle, Info, 'help-circle': HelpCircle,
  Facebook, Twitter, Instagram, Youtube, Linkedin, Github,
  'shopping-cart': ShoppingCart, 'credit-card': CreditCard, 'trending-up': TrendingUp, 'bar-chart': BarChart,
  Palette, Brush, Wand, Sparkles, Flame, Zap,
  Pizza, Coffee, Beer, Cake, 'ice-cream': IceCream, Cookie,
  Target, Crosshair, Shield, Swords, Trophy, Medal,
  Gamepad2, Monitor, Clock, Calendar, 'map-pin': MapPin, Phone,
  Send, 'message-square': MessageSquare, Bot, Users, Star, Heart,
  Eye, Play, Pause, 'volume-2': Volume2, 'volume-x': VolumeX, Maximize,
  Filter, 'sort-asc': SortAsc, Grid, List, 'layout-grid': LayoutGrid,
  Skull, Bomb, Radio, Headphones, Mic, 'mic-off': MicOff,
  Flag, Map, Navigation, Compass, Globe,
  'chevron-down': ChevronDown, 'chevron-up': ChevronUp, 'arrow-up': ArrowUp, 'arrow-down': ArrowDown,
  'refresh-cw': RefreshCw, 'rotate-ccw': RotateCcw, Loader2, Activity,
  Lock, Unlock, Key, 'log-in': LogIn, 'log-out': LogOut,
  'file-text': FileText, Image, Video, Music, File,
  Folder, Archive, Upload, Cloud, Database,
  Wifi, Bluetooth, Battery, 'battery-charging': BatteryCharging,
  Sun, Moon, 'monitor-play': MonitorPlay, Tv, Smartphone,
  Laptop, Mouse, Keyboard, Printer, Camera,
  'shopping-bag': ShoppingBag, Tag, Percent, Gift, Award,
  Briefcase, Building, Landmark, Wallet,
  Plane, Car, Bus, Train, Ship, Truck,
  'home-icon': HomeIcon, Building2, Store, Warehouse,
  'tree-pine': TreePine, 'flower-2': Flower2, Mountain, Waves, 'cloud-sun': CloudSun,
  Thermometer, Droplets, Wind, 'cloud-rain': CloudRain, Snowflake,
  'alert-triangle': AlertTriangle, 'alert-octagon': AlertOctagon, 'shield-alert': ShieldAlert,
  'help-square': HelpSquare, 'book-open': BookOpen, 'graduation-cap': GraduationCap, Lightbulb,
  Puzzle, Blocks, Box, Package, Container,
  Scissors, 'pen-tool': PenTool, Type, 'align-left': AlignLeft, 'align-center': AlignCenter,
  Bold, Italic, Underline, Link, Paperclip,
  'more-horizontal': MoreHorizontal, 'more-vertical': MoreVertical, 'grip-vertical': GripVertical,
  Minus, Divide, Equal, 'percent-icon': Percent,
  Hash, At, 'dollar-sign': DollarSign, Euro, 'pound-sterling': PoundSterling,
  Bitcoin, Banknote, Coins, Receipt,
  'qr-code': QrCode, Barcode, Scan, 'scan-line': ScanLine,
  Fingerprint, 'face-id': ScanFace, 'scan-face': ScanFace,
  Accessibility, Ear, 'eye-off': EyeOff, Glasses,
  'heart-pulse': HeartPulse, 'activity-square': Activity, Stethoscope,
  Pill, Syringe, 'thermometer-snowflake': ThermometerSnowflake,
  Dumbbell, Bike, Swim, Footprints,
  Tent, Campfire, Fish, Beef, Apple,
  Cherry, Grape, Citrus, Carrot,
  Utensils, 'fork-knife': ForkKnife, Soup, Salad,
  Sandwich, Hamburger, Hotdog, Fries,
  Popcorn, Donut, 'cup-soda': CupSoda, Wine,
  'glass-water': GlassWater, Milk, Egg, Croissant,
  Toast, Soup2, Drumstick, Bacon
};

const SafeIcon = ({ name, size = 24, className = '', color }) => {
  const IconComponent = iconMap[name] || HelpCircle;
  
  return (
    <IconComponent 
      size={size} 
      className={className} 
      color={color}
    />
  );
};

export default SafeIcon;